import Navbar from '@/components/shared/Navbar';

import type { Metadata } from 'next';

import { ThemeProvider } from 'next-themes';

export const metadata: Metadata = {
  title: 'Next Auth Dashboard',
  description: 'Generated by create next app',
};

export default async function CommonLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <div className="min-h-screen my-2">
      <div>
        <div>
          <Navbar />
          <ThemeProvider attribute="class">{children}</ThemeProvider>
        </div>
      </div>
    </div>
  );
}
